---
title: "Statistical Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Revised model.

```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(xtable)
library(MASS)
library(knitr)
library(pscl)
library(stargazer)
library(dplyr)
library(pastecs)
library(gmodels)
library(readxl)
library(foreign)
library(nnet)
library(stargazer)
```

```{r, echo=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
#Read the dataset
license.df<-read_xlsx("Data/upload_date.xlsx",1)
#Create the factors
license.df$license<-as.factor(license.df$license)
license.df$Type <-as.factor(license.df$Type )
#Call the mlogit library
license.df<-na.omit(license.df)
license.df$license = relevel(license.df$license, ref = "Creative Commons - Attribution - Share Alike")

#Classify
license.df <- license.df %>% 
               mutate(license.choice=
                        ifelse(license %in% c("All Rights Reserved",   "Attribution - Non-Commercial - No Derivatives","Attribution - Non-Commercial - Share Alike","Creative Commons - Attribution - Non-Commercial"),"1",   ifelse(license %in% c("BSD License", "Creative Commons - Attribution", "Creative Commons - Attribution - Share Alike"),"2",
                        ifelse(license %in% c("Creative Commons - Attribution - No Derivatives"),"1","3"))))

#Key event
license.df<-license.df %>% 
  mutate(key.event=ifelse(upload_date<"2012-09-24","1",
                   ifelse(upload_date<"2013-11-05","2","3")))

#
temp <- license.df %>% 
             group_by(thing_author_id,key.event) %>% 
              summarize(n_conut = n(),
              larger  = sum(inv > 0),
              zero = sum(inv == 0))
#Classify
temp <- temp %>% 
        mutate(appropriability_strategy=ifelse(larger>0 & zero>0,"private-collective",
                      ifelse(larger>0 & zero==0, "free-riding","private"))) %>% 
        select(-n_conut,-larger,-zero)
#Convert to factor
temp$appropriability_strategy<-as.factor(temp$appropriability_strategy)   

#Join with the license.df
license.df <- full_join(license.df, temp, by=c("thing_author_id","key.event"))

#Define the reference (free-riding)
license.df <- within(license.df, appropriability_strategy <- relevel(appropriability_strategy, ref = "free-riding"))
```


```{r, echo=TRUE,eval=TRUE,message=FALSE,warning=FALSE, message=FALSE, warning=FALSE}
#Call the library
multi1 <- multinom(license.choice~1+files_count+thing_like_count+collection_count+key.event, data=license.df, maxit = 10000)

```


```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Estimates
stargazer(multi1, type="html", out="multi1_12_04_2017_free_riding.htm")
```

```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Relative risk ratios
multi1.rrr = exp(coef(multi1))
stargazer(multi1, coef=list(multi1.rrr), p.auto=FALSE,  type="html", out="rrrmulti1_12_04_2017_free_riding.htm")
```

```{r, echo=TRUE,eval=TRUE,message=FALSE,warning=FALSE, message=FALSE, warning=FALSE}
#Call the library
multi1 <- multinom(license.choice~1+ files_count+thing_like_count+collection_count+key.event+appropriability_strategy, data=license.df, maxit = 10000)

```


```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Estimates
stargazer(multi1, type="html", out="multi2_12_04_2017_free_riding.htm")
```

```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Relative risk ratios
multi1.rrr = exp(coef(multi1))
stargazer(multi1, coef=list(multi1.rrr), p.auto=FALSE,  type="html", out="rrrmulti2_12_04_2017_free_riding.htm")
```

```{r, echo=TRUE,eval=TRUE,message=FALSE,warning=FALSE, message=FALSE, warning=FALSE}
#Call the library
multi1 <- multinom(license.choice~1+  files_count+thing_like_count+collection_count+key.event+appropriability_strategy+(appropriability_strategy*key.event), data=license.df, maxit = 10000)
```


```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Estimates
stargazer(multi1, type="html", out="multi3_12_04_2017_free_riding.htm")
```

```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE, results='asis'}
#Relative risk ratios
multi1.rrr = exp(coef(multi1))
stargazer(multi1, coef=list(multi1.rrr), p.auto=FALSE,  type="html", out="rrrmulti3_12_04_2017_free_riding.htm")
```