---
title: "Statistical Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##George message 3.
Pedro, 

Further to our discussion yesterday, below I'll try to expand the underlying ideas without me writing an essay or too much abstract/theoretical stuff. 

Can you do the following please. 

Can you use individual designer as our unit of analysis.
That's, by collating and aggregating contribution of each designer, our unit of analysis becomes the designer's design portfolio. Somehow we need to retain the time information considering the key events that may affect designer's contribution. For example, when Makerbot decided to make hardware closed source (see the attached Makerbot Timeline for other events). One of the caveats is that the data will become too sparse as some contributors may not consistently contribute over time. This will result in an unbalanced panel. But give and take, we need to account for two key incidents:  event number 4 (happened in 24.09.2012), and number 8 (05.11.2013). We use these two time points to temporally divide our data into three periods: prior to closed source will be the first period, followed by the period after closed source announcement, until patent infringement and from that onwards our third period.
Create a category of design strategy based on the "in" column. First, if the in column is larger than 0 (i.e. in >0), then it means the design is NOT an original design, and is a derivative of prior design. Followed from this, if the in column = 0 (i.e. in = 0), then the design is original.  We can use these two pieces of information to construct three types of design strategy: free riding (where there are zero counts of in=0 but non-zero counts of in>0); private (non-zero counts of in=0 but zero counts of in > 0), and blended (non-zero counts of  in>0 &  of in=0). For example, a designer contributed 10 designs, say 5 designs with in>0, and the other 5 with in=0. Then, this designer is using a blended design strategy. The second designer shared 20 designs, however, all of her designs are derived from others' designers work (i.e. non-zero counts of n>0  but zero counts of n=0). This designer is using a free-riding (or mesh-up) design strategy. Lastly, the third designer is using a private strategy when there are zero counts of in>0, but non-zero counts of in=0).  The theoretical prediction is that the blended strategy (with private and public interests) will more likely to attract substantial creative attention from other designers than the other two design strategies. The blended strategy reflected the fact that the first designer juxtaposed private with collective interests, this resulted in positive returns in two ways: there will be more derivatives (the out column) on his original designs, and the same also applies to that his meshup designs. Also both "private/original" and "meshed-up" designs will more likely to be printed (the made-count columns). Here we need to make a fine grainer analysis, that designers that used blended strategy are combining private with collective interests whereas designers who purely pursue their own private agenda by posting original designs are less likely to attract attention and contribution from others. 
We use the licence types to identify several types of entrepreneurial strategy (ES): a. designs are shared under the most restrictive licences to mitigate business rivalry. So this includes any licences that discouraged commercial activities. The two main licences are "All Rights Reserved", "Attribution - Non-Commercial - No Derivatives", and "Creative Commons - Attribution - Non-Commercial); b. the use of the least restrictive licences to induce contributions from business and social actors. They are: "BSD License", "Creative Commons - Attribution", "Creative Commons- Attribution - Shake Alike"; d. the third type of ES is to mitigate social rivalry. The licenses are: "Creative Commons - Attribution - No Derivatives"; e the final fourth type is anti-business. They are: "Creative Commons - Public Domain Dedication", "GNU - GPL", "GNU - LGPL", and "Public Domain". We then aggregate the license use of each design across these four types of ES. So from the first ES (ES_1) the designers want to protect their business interest. With the second strategy (ES_2), the designers (are likely to be a serial inventor)  happily give away their designs for others to explore and exploit (as it allows others to reuse, commercialise, and/or make a derivative of his design). The third ES (ES_3) underlines the motives of the designers in competition for social status. And from the fourth type (ES_4), the designers are more likely to be driven by ideological and/or philosophical reasons. So I can predict that ES_2 will attract more attention than the other groups. At this stage, I'd run an inductive analysis by examining the relationship between the four ES types and our dependent measures (out, and made_count) to fine tune my prediction. So we need to discuss this when you come to this point in time. Consider the high likelihood that license types may be subject to the two critical events (see point 2 re close source and patent). A designer could be ES_2 in the first period, but switched to ES_4 in periods 2 and 3. Others would release certain designs under a mixed licence arrangement: ES_3 and ES_4 for example. And also many designers may leave the community and stop contribution. I think these patterns are really interesting. I predict that designers, who are serial inventor and primarily adopt ES_2, will be the least affected. Can you test this prediction. 
Lastly, I think it's the most interesting but need more data exploration are the interaction effects between ES x design strategy. I will predict the interaction between "blended strategy" x "entrepreneurial strategy type 2" are more likely to increase derivative and made_count. 

I hope the above makes some sense. I will be working 7 days a week from now on. SO please don't hesitate to contact me. 

George


